import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StrapiApolloProvider from '@/graphql/apollo'
import Navigation from './components/Navigation'
import { AppProvider } from './context/AppContext'
import Cart from './components/Cart/Cart'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StrapiApolloProvider>
          <AppProvider>

            <div className="page">
              <Navigation />
              <Cart />
              {children}
            </div>

          </AppProvider>
        </StrapiApolloProvider>
      </body>
    </html>
  )
}
